apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - security.yaml
  - postgres.yaml
  - server-configmap.yaml
  - ai-context-configmap.yaml
  - server-deployment.yaml
  - server-service.yaml
