apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: adp
  labels:
    app.kubernetes.io/name: postgres
    app.kubernetes.io/part-of: adp
type: Opaque
stringData:
  POSTGRES_USER: "postgres"
  POSTGRES_PASSWORD: "change-me"
  POSTGRES_DB: "adp"
