apiVersion: v1
kind: Service
metadata:
  name: adp-server
  namespace: adp
  labels:
    app.kubernetes.io/name: adp-server
    app.kubernetes.io/part-of: adp
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: adp-server
  ports:
    - name: http
      port: 8080
      targetPort: http
      nodePort: 30081
