// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: api/proto/adp/v1/worker.proto

package adpv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type WorkerEnvelope struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*WorkerEnvelope_Register
	//	*WorkerEnvelope_Heartbeat
	//	*WorkerEnvelope_JobResult
	//	*WorkerEnvelope_CommandAck
	Payload       isWorkerEnvelope_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkerEnvelope) Reset() {
	*x = WorkerEnvelope{}
	mi := &file_api_proto_adp_v1_worker_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkerEnvelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkerEnvelope) ProtoMessage() {}

func (x *WorkerEnvelope) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_adp_v1_worker_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkerEnvelope.ProtoReflect.Descriptor instead.
func (*WorkerEnvelope) Descriptor() ([]byte, []int) {
	return file_api_proto_adp_v1_worker_proto_rawDescGZIP(), []int{0}
}

func (x *WorkerEnvelope) GetPayload() isWorkerEnvelope_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *WorkerEnvelope) GetRegister() *RegisterRequest {
	if x != nil {
		if x, ok := x.Payload.(*WorkerEnvelope_Register); ok {
			return x.Register
		}
	}
	return nil
}

func (x *WorkerEnvelope) GetHeartbeat() *Heartbeat {
	if x != nil {
		if x, ok := x.Payload.(*WorkerEnvelope_Heartbeat); ok {
			return x.Heartbeat
		}
	}
	return nil
}

func (x *WorkerEnvelope) GetJobResult() *JobResult {
	if x != nil {
		if x, ok := x.Payload.(*WorkerEnvelope_JobResult); ok {
			return x.JobResult
		}
	}
	return nil
}

func (x *WorkerEnvelope) GetCommandAck() *CommandAck {
	if x != nil {
		if x, ok := x.Payload.(*WorkerEnvelope_CommandAck); ok {
			return x.CommandAck
		}
	}
	return nil
}

type isWorkerEnvelope_Payload interface {
	isWorkerEnvelope_Payload()
}

type WorkerEnvelope_Register struct {
	Register *RegisterRequest `protobuf:"bytes,1,opt,name=register,proto3,oneof"`
}

type WorkerEnvelope_Heartbeat struct {
	Heartbeat *Heartbeat `protobuf:"bytes,2,opt,name=heartbeat,proto3,oneof"`
}

type WorkerEnvelope_JobResult struct {
	JobResult *JobResult `protobuf:"bytes,3,opt,name=job_result,json=jobResult,proto3,oneof"`
}

type WorkerEnvelope_CommandAck struct {
	CommandAck *CommandAck `protobuf:"bytes,4,opt,name=command_ack,json=commandAck,proto3,oneof"`
}

func (*WorkerEnvelope_Register) isWorkerEnvelope_Payload() {}

func (*WorkerEnvelope_Heartbeat) isWorkerEnvelope_Payload() {}

func (*WorkerEnvelope_JobResult) isWorkerEnvelope_Payload() {}

func (*WorkerEnvelope_CommandAck) isWorkerEnvelope_Payload() {}

type ServerEnvelope struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*ServerEnvelope_Registered
	//	*ServerEnvelope_Job
	//	*ServerEnvelope_Command
	//	*ServerEnvelope_Error
	Payload       isServerEnvelope_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerEnvelope) Reset() {
	*x = ServerEnvelope{}
	mi := &file_api_proto_adp_v1_worker_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerEnvelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerEnvelope) ProtoMessage() {}

func (x *ServerEnvelope) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_adp_v1_worker_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerEnvelope.ProtoReflect.Descriptor instead.
func (*ServerEnvelope) Descriptor() ([]byte, []int) {
	return file_api_proto_adp_v1_worker_proto_rawDescGZIP(), []int{1}
}

func (x *ServerEnvelope) GetPayload() isServerEnvelope_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *ServerEnvelope) GetRegistered() *RegisterResponse {
	if x != nil {
		if x, ok := x.Payload.(*ServerEnvelope_Registered); ok {
			return x.Registered
		}
	}
	return nil
}

func (x *ServerEnvelope) GetJob() *Job {
	if x != nil {
		if x, ok := x.Payload.(*ServerEnvelope_Job); ok {
			return x.Job
		}
	}
	return nil
}

func (x *ServerEnvelope) GetCommand() string {
	if x != nil {
		if x, ok := x.Payload.(*ServerEnvelope_Command); ok {
			return x.Command
		}
	}
	return ""
}

func (x *ServerEnvelope) GetError() string {
	if x != nil {
		if x, ok := x.Payload.(*ServerEnvelope_Error); ok {
			return x.Error
		}
	}
	return ""
}

type isServerEnvelope_Payload interface {
	isServerEnvelope_Payload()
}

type ServerEnvelope_Registered struct {
	Registered *RegisterResponse `protobuf:"bytes,1,opt,name=registered,proto3,oneof"`
}

type ServerEnvelope_Job struct {
	Job *Job `protobuf:"bytes,2,opt,name=job,proto3,oneof"`
}

type ServerEnvelope_Command struct {
	Command string `protobuf:"bytes,3,opt,name=command,proto3,oneof"`
}

type ServerEnvelope_Error struct {
	Error string `protobuf:"bytes,4,opt,name=error,proto3,oneof"`
}

func (*ServerEnvelope_Registered) isServerEnvelope_Payload() {}

func (*ServerEnvelope_Job) isServerEnvelope_Payload() {}

func (*ServerEnvelope_Command) isServerEnvelope_Payload() {}

func (*ServerEnvelope_Error) isServerEnvelope_Payload() {}

type RegisterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	WorkerType    string                 `protobuf:"bytes,2,opt,name=worker_type,json=workerType,proto3" json:"worker_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_api_proto_adp_v1_worker_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_adp_v1_worker_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_adp_v1_worker_proto_rawDescGZIP(), []int{2}
}

func (x *RegisterRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RegisterRequest) GetWorkerType() string {
	if x != nil {
		return x.WorkerType
	}
	return ""
}

type RegisterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkerId      string                 `protobuf:"bytes,1,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	WorkerType    string                 `protobuf:"bytes,3,opt,name=worker_type,json=workerType,proto3" json:"worker_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterResponse) Reset() {
	*x = RegisterResponse{}
	mi := &file_api_proto_adp_v1_worker_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResponse) ProtoMessage() {}

func (x *RegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_adp_v1_worker_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterResponse.ProtoReflect.Descriptor instead.
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_adp_v1_worker_proto_rawDescGZIP(), []int{3}
}

func (x *RegisterResponse) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

func (x *RegisterResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RegisterResponse) GetWorkerType() string {
	if x != nil {
		return x.WorkerType
	}
	return ""
}

type Heartbeat struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkerId      string                 `protobuf:"bytes,1,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	HostInfo      *HostInfo              `protobuf:"bytes,2,opt,name=host_info,json=hostInfo,proto3" json:"host_info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Heartbeat) Reset() {
	*x = Heartbeat{}
	mi := &file_api_proto_adp_v1_worker_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Heartbeat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Heartbeat) ProtoMessage() {}

func (x *Heartbeat) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_adp_v1_worker_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Heartbeat.ProtoReflect.Descriptor instead.
func (*Heartbeat) Descriptor() ([]byte, []int) {
	return file_api_proto_adp_v1_worker_proto_rawDescGZIP(), []int{4}
}

func (x *Heartbeat) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

func (x *Heartbeat) GetHostInfo() *HostInfo {
	if x != nil {
		return x.HostInfo
	}
	return nil
}

type HostInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hostname      string                 `protobuf:"bytes,1,opt,name=hostname,proto3" json:"hostname,omitempty"`
	IpAddress     string                 `protobuf:"bytes,2,opt,name=ip_address,json=ipAddress,proto3" json:"ip_address,omitempty"`
	CpuUsage      float64                `protobuf:"fixed64,3,opt,name=cpu_usage,json=cpuUsage,proto3" json:"cpu_usage,omitempty"`
	StorageUsage  float64                `protobuf:"fixed64,4,opt,name=storage_usage,json=storageUsage,proto3" json:"storage_usage,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HostInfo) Reset() {
	*x = HostInfo{}
	mi := &file_api_proto_adp_v1_worker_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HostInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HostInfo) ProtoMessage() {}

func (x *HostInfo) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_adp_v1_worker_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HostInfo.ProtoReflect.Descriptor instead.
func (*HostInfo) Descriptor() ([]byte, []int) {
	return file_api_proto_adp_v1_worker_proto_rawDescGZIP(), []int{5}
}

func (x *HostInfo) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *HostInfo) GetIpAddress() string {
	if x != nil {
		return x.IpAddress
	}
	return ""
}

func (x *HostInfo) GetCpuUsage() float64 {
	if x != nil {
		return x.CpuUsage
	}
	return 0
}

func (x *HostInfo) GetStorageUsage() float64 {
	if x != nil {
		return x.StorageUsage
	}
	return 0
}

type Job struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	WorkerType    string                 `protobuf:"bytes,3,opt,name=worker_type,json=workerType,proto3" json:"worker_type,omitempty"`
	Command       string                 `protobuf:"bytes,4,opt,name=command,proto3" json:"command,omitempty"`
	TemplateCode  string                 `protobuf:"bytes,5,opt,name=template_code,json=templateCode,proto3" json:"template_code,omitempty"`
	Parameters    map[string]string      `protobuf:"bytes,6,rep,name=parameters,proto3" json:"parameters,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Job) Reset() {
	*x = Job{}
	mi := &file_api_proto_adp_v1_worker_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Job) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Job) ProtoMessage() {}

func (x *Job) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_adp_v1_worker_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Job.ProtoReflect.Descriptor instead.
func (*Job) Descriptor() ([]byte, []int) {
	return file_api_proto_adp_v1_worker_proto_rawDescGZIP(), []int{6}
}

func (x *Job) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Job) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Job) GetWorkerType() string {
	if x != nil {
		return x.WorkerType
	}
	return ""
}

func (x *Job) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

func (x *Job) GetTemplateCode() string {
	if x != nil {
		return x.TemplateCode
	}
	return ""
}

func (x *Job) GetParameters() map[string]string {
	if x != nil {
		return x.Parameters
	}
	return nil
}

type JobResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkerId      string                 `protobuf:"bytes,1,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	JobId         string                 `protobuf:"bytes,2,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	Command       string                 `protobuf:"bytes,3,opt,name=command,proto3" json:"command,omitempty"`
	Success       bool                   `protobuf:"varint,4,opt,name=success,proto3" json:"success,omitempty"`
	Output        string                 `protobuf:"bytes,5,opt,name=output,proto3" json:"output,omitempty"`
	LogToDb       bool                   `protobuf:"varint,6,opt,name=log_to_db,json=logToDb,proto3" json:"log_to_db,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JobResult) Reset() {
	*x = JobResult{}
	mi := &file_api_proto_adp_v1_worker_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JobResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobResult) ProtoMessage() {}

func (x *JobResult) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_adp_v1_worker_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobResult.ProtoReflect.Descriptor instead.
func (*JobResult) Descriptor() ([]byte, []int) {
	return file_api_proto_adp_v1_worker_proto_rawDescGZIP(), []int{7}
}

func (x *JobResult) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

func (x *JobResult) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *JobResult) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

func (x *JobResult) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *JobResult) GetOutput() string {
	if x != nil {
		return x.Output
	}
	return ""
}

func (x *JobResult) GetLogToDb() bool {
	if x != nil {
		return x.LogToDb
	}
	return false
}

type CommandAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkerId      string                 `protobuf:"bytes,1,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	Command       string                 `protobuf:"bytes,2,opt,name=command,proto3" json:"command,omitempty"`
	Success       bool                   `protobuf:"varint,3,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommandAck) Reset() {
	*x = CommandAck{}
	mi := &file_api_proto_adp_v1_worker_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommandAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandAck) ProtoMessage() {}

func (x *CommandAck) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_adp_v1_worker_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandAck.ProtoReflect.Descriptor instead.
func (*CommandAck) Descriptor() ([]byte, []int) {
	return file_api_proto_adp_v1_worker_proto_rawDescGZIP(), []int{8}
}

func (x *CommandAck) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

func (x *CommandAck) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

func (x *CommandAck) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_api_proto_adp_v1_worker_proto protoreflect.FileDescriptor

const file_api_proto_adp_v1_worker_proto_rawDesc = "" +
	"\n" +
	"\x1dapi/proto/adp/v1/worker.proto\x12\x06adp.v1\"\xf0\x01\n" +
	"\x0eWorkerEnvelope\x125\n" +
	"\bregister\x18\x01 \x01(\v2\x17.adp.v1.RegisterRequestH\x00R\bregister\x121\n" +
	"\theartbeat\x18\x02 \x01(\v2\x11.adp.v1.HeartbeatH\x00R\theartbeat\x122\n" +
	"\n" +
	"job_result\x18\x03 \x01(\v2\x11.adp.v1.JobResultH\x00R\tjobResult\x125\n" +
	"\vcommand_ack\x18\x04 \x01(\v2\x12.adp.v1.CommandAckH\x00R\n" +
	"commandAckB\t\n" +
	"\apayload\"\xac\x01\n" +
	"\x0eServerEnvelope\x12:\n" +
	"\n" +
	"registered\x18\x01 \x01(\v2\x18.adp.v1.RegisterResponseH\x00R\n" +
	"registered\x12\x1f\n" +
	"\x03job\x18\x02 \x01(\v2\v.adp.v1.JobH\x00R\x03job\x12\x1a\n" +
	"\acommand\x18\x03 \x01(\tH\x00R\acommand\x12\x16\n" +
	"\x05error\x18\x04 \x01(\tH\x00R\x05errorB\t\n" +
	"\apayload\"F\n" +
	"\x0fRegisterRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1f\n" +
	"\vworker_type\x18\x02 \x01(\tR\n" +
	"workerType\"d\n" +
	"\x10RegisterResponse\x12\x1b\n" +
	"\tworker_id\x18\x01 \x01(\tR\bworkerId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1f\n" +
	"\vworker_type\x18\x03 \x01(\tR\n" +
	"workerType\"W\n" +
	"\tHeartbeat\x12\x1b\n" +
	"\tworker_id\x18\x01 \x01(\tR\bworkerId\x12-\n" +
	"\thost_info\x18\x02 \x01(\v2\x10.adp.v1.HostInfoR\bhostInfo\"\x87\x01\n" +
	"\bHostInfo\x12\x1a\n" +
	"\bhostname\x18\x01 \x01(\tR\bhostname\x12\x1d\n" +
	"\n" +
	"ip_address\x18\x02 \x01(\tR\tipAddress\x12\x1b\n" +
	"\tcpu_usage\x18\x03 \x01(\x01R\bcpuUsage\x12#\n" +
	"\rstorage_usage\x18\x04 \x01(\x01R\fstorageUsage\"\x85\x02\n" +
	"\x03Job\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1f\n" +
	"\vworker_type\x18\x03 \x01(\tR\n" +
	"workerType\x12\x18\n" +
	"\acommand\x18\x04 \x01(\tR\acommand\x12#\n" +
	"\rtemplate_code\x18\x05 \x01(\tR\ftemplateCode\x12;\n" +
	"\n" +
	"parameters\x18\x06 \x03(\v2\x1b.adp.v1.Job.ParametersEntryR\n" +
	"parameters\x1a=\n" +
	"\x0fParametersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xa7\x01\n" +
	"\tJobResult\x12\x1b\n" +
	"\tworker_id\x18\x01 \x01(\tR\bworkerId\x12\x15\n" +
	"\x06job_id\x18\x02 \x01(\tR\x05jobId\x12\x18\n" +
	"\acommand\x18\x03 \x01(\tR\acommand\x12\x18\n" +
	"\asuccess\x18\x04 \x01(\bR\asuccess\x12\x16\n" +
	"\x06output\x18\x05 \x01(\tR\x06output\x12\x1a\n" +
	"\tlog_to_db\x18\x06 \x01(\bR\alogToDb\"]\n" +
	"\n" +
	"CommandAck\x12\x1b\n" +
	"\tworker_id\x18\x01 \x01(\tR\bworkerId\x12\x18\n" +
	"\acommand\x18\x02 \x01(\tR\acommand\x12\x18\n" +
	"\asuccess\x18\x03 \x01(\bR\asuccess2M\n" +
	"\rWorkerService\x12<\n" +
	"\x06Stream\x12\x16.adp.v1.WorkerEnvelope\x1a\x16.adp.v1.ServerEnvelope(\x010\x01B\x1cZ\x1aadp/api/proto/adp/v1;adpv1b\x06proto3"

var (
	file_api_proto_adp_v1_worker_proto_rawDescOnce sync.Once
	file_api_proto_adp_v1_worker_proto_rawDescData []byte
)

func file_api_proto_adp_v1_worker_proto_rawDescGZIP() []byte {
	file_api_proto_adp_v1_worker_proto_rawDescOnce.Do(func() {
		file_api_proto_adp_v1_worker_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_adp_v1_worker_proto_rawDesc), len(file_api_proto_adp_v1_worker_proto_rawDesc)))
	})
	return file_api_proto_adp_v1_worker_proto_rawDescData
}

var file_api_proto_adp_v1_worker_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_api_proto_adp_v1_worker_proto_goTypes = []any{
	(*WorkerEnvelope)(nil),   // 0: adp.v1.WorkerEnvelope
	(*ServerEnvelope)(nil),   // 1: adp.v1.ServerEnvelope
	(*RegisterRequest)(nil),  // 2: adp.v1.RegisterRequest
	(*RegisterResponse)(nil), // 3: adp.v1.RegisterResponse
	(*Heartbeat)(nil),        // 4: adp.v1.Heartbeat
	(*HostInfo)(nil),         // 5: adp.v1.HostInfo
	(*Job)(nil),              // 6: adp.v1.Job
	(*JobResult)(nil),        // 7: adp.v1.JobResult
	(*CommandAck)(nil),       // 8: adp.v1.CommandAck
	nil,                      // 9: adp.v1.Job.ParametersEntry
}
var file_api_proto_adp_v1_worker_proto_depIdxs = []int32{
	2, // 0: adp.v1.WorkerEnvelope.register:type_name -> adp.v1.RegisterRequest
	4, // 1: adp.v1.WorkerEnvelope.heartbeat:type_name -> adp.v1.Heartbeat
	7, // 2: adp.v1.WorkerEnvelope.job_result:type_name -> adp.v1.JobResult
	8, // 3: adp.v1.WorkerEnvelope.command_ack:type_name -> adp.v1.CommandAck
	3, // 4: adp.v1.ServerEnvelope.registered:type_name -> adp.v1.RegisterResponse
	6, // 5: adp.v1.ServerEnvelope.job:type_name -> adp.v1.Job
	5, // 6: adp.v1.Heartbeat.host_info:type_name -> adp.v1.HostInfo
	9, // 7: adp.v1.Job.parameters:type_name -> adp.v1.Job.ParametersEntry
	0, // 8: adp.v1.WorkerService.Stream:input_type -> adp.v1.WorkerEnvelope
	1, // 9: adp.v1.WorkerService.Stream:output_type -> adp.v1.ServerEnvelope
	9, // [9:10] is the sub-list for method output_type
	8, // [8:9] is the sub-list for method input_type
	8, // [8:8] is the sub-list for extension type_name
	8, // [8:8] is the sub-list for extension extendee
	0, // [0:8] is the sub-list for field type_name
}

func init() { file_api_proto_adp_v1_worker_proto_init() }
func file_api_proto_adp_v1_worker_proto_init() {
	if File_api_proto_adp_v1_worker_proto != nil {
		return
	}
	file_api_proto_adp_v1_worker_proto_msgTypes[0].OneofWrappers = []any{
		(*WorkerEnvelope_Register)(nil),
		(*WorkerEnvelope_Heartbeat)(nil),
		(*WorkerEnvelope_JobResult)(nil),
		(*WorkerEnvelope_CommandAck)(nil),
	}
	file_api_proto_adp_v1_worker_proto_msgTypes[1].OneofWrappers = []any{
		(*ServerEnvelope_Registered)(nil),
		(*ServerEnvelope_Job)(nil),
		(*ServerEnvelope_Command)(nil),
		(*ServerEnvelope_Error)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_adp_v1_worker_proto_rawDesc), len(file_api_proto_adp_v1_worker_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_adp_v1_worker_proto_goTypes,
		DependencyIndexes: file_api_proto_adp_v1_worker_proto_depIdxs,
		MessageInfos:      file_api_proto_adp_v1_worker_proto_msgTypes,
	}.Build()
	File_api_proto_adp_v1_worker_proto = out.File
	file_api_proto_adp_v1_worker_proto_goTypes = nil
	file_api_proto_adp_v1_worker_proto_depIdxs = nil
}
