apiVersion: apps/v1
kind: Deployment
metadata:
  name: adp-server
spec:
  template:
    spec:
      imagePullSecrets:
        - name: ghcr-secret
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: adp-worker
spec:
  template:
    spec:
      imagePullSecrets:
        - name: ghcr-secret
