apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - sealed-adp-runtime.yaml

images:
  - name: adp-server
    newName: ghcr.io/fff-rick/adp-server
    newTag: aee6758a0e57510047c94259486ef4a90e01736b

patchesStrategicMerge:
  - image-pull-secrets.yaml
