apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: adp

resources:
  - ../../base
  - secrets/sealed-postgres-secret.yaml
  - secrets/sealed-adp-server-secret.yaml

images:
  - name: ghcr.io/fff-rick/adp-server
    newName: ghcr.io/fff-rick/adp-server
    newTag: v1.0

patches:
  - path: server-config.patch.yaml
