apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: adp

resources:
  - ../../base
  - secrets/sealed-postgres-secret.yaml
  - secrets/sealed-adp-server-secret.yaml

images:
  - name: ghcr.io/fff-rick/adp-server
    newName: ghcr.io/fff-rick/adp-server
    newTag: 8f935e0ba8f3                  # tag占位，不用指定，自动更新为新提交的sha

patches:
  - path: server-config.patch.yaml
