apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: adp
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/fff-rick/ADP-fff-rick.git
    targetRevision: main
    path: deploy/k8s/overlays/prod
  destination:
    namespace: adp
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
